allLaptops = {
    brands: ["Acer", "Apple", "Dell", "HP"],
    categories: ["brand", "processor", "ram", "rating", "hardDisk"],
    laptops: [
      {
        model: "AX4581",
        brand: "Acer",
        ram: "6GB",
        mrp: "150$",
        price: "24$",
        hardDisk: "500GB",
        rating: "3",
        processor: "i3",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt01.jpeg",
      },
      {
        model: "HB2881",
        brand: "HP",
        ram: "4GB",
        mrp: "150$",
        price: "27$",
        hardDisk: "250GB",
        rating: "4",
        processor: "i3",
        quantity: 0,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt02.jpeg",
      },
      {
        model: "DM811",
        brand: "Dell",
        ram: "4GB",
        mrp: "110$",
        price: "25$",
        hardDisk: "1TB",
        rating: "3",
        processor: "i3",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt03.jpeg",
      },
      {
        model: "AP629",
        brand: "Acer",
        ram: "6GB",
        mrp: "130$",
        price: "50$",
        hardDisk: "1TB",
        rating: "2",
        processor: "i3",
        quantity: 0,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt04.jpeg",
      },
      {
        model: "AT820",
        brand: "Acer",
        ram: "6GB",
        mrp: "100$",
        price: "70$",
        hardDisk: "1TB",
        rating: "4",
        processor: "i5",
        quantity: 0,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt01.jpeg",
      },
      {
        model: "HK008",
        brand: "HP",
        ram: "4GB",
        mrp: "90$",
        price: "50$",
        hardDisk: "250GB",
        rating: "3",
        processor: "i5",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt02.jpeg",
      },
      {
        model: "MAir11",
        brand: "Apple",
        ram: "8GB",
        mrp: "110$",
        price: "90$",
        hardDisk: "128GB",
        rating: "4",
        processor: "i5",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt03.jpeg",
      },
      {
        model: "MPro24X",
        brand: "Apple",
        ram: "8GB",
        mrp: "150$",
        price: "110$",
        hardDisk: "256GB",
        rating: "4",
        processor: "i7",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt04.jpeg",
      },
      {
        model: "DL390",
        brand: "Dell",
        ram: "6GB",
        mrp: "100$",
        price: "50$",
        hardDisk: "500GB",
        rating: "3",
        processor: "i3",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt01.jpeg",
      },
      {
        model: "AM954",
        brand: "Acer",
        ram: "4GB",
        mrp: "95$",
        price: "80$",
        hardDisk: "1TB",
        rating: "3",
        processor: "i7",
        quantity: 0,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt02.jpeg",
      },
      {
        model: "AB234",
        brand: "Acer",
        ram: "6GB",
        mrp: "50$",
        price: "30$",
        hardDisk: "250GB",
        rating: "2",
        processor: "i3",
        quantity: 10,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt03.jpeg",
      },
      {
        model: "HC874",
        brand: "HP",
        ram: "8GB",
        mrp: "50$",
        price: "40$",
        hardDisk: "1TB",
        rating: "1",
        processor: "i7",
        quantity: 0,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt04.jpeg",
      },
      {
        model: "AN2015M",
        brand: "Acer",
        ram: "8GB",
        mrp: "99$",
        price: "80$",
        hardDisk: "1TB",
        rating: "4",
        processor: "i5",
        quantity: 3,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt01.jpeg",
      },
      {
        model: "AB235P",
        brand: "Acer",
        ram: "8GB",
        mrp: "50$",
        price: "30$",
        hardDisk: "500GB",
        rating: "3",
        processor: "i5",
        quantity: 2,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt02.jpeg",
      },
      {
        model: "HV5612",
        brand: "HP",
        ram: "4GB",
        mrp: "120$",
        price: "80$",
        hardDisk: "1TB",
        rating: "5",
        processor: "i7",
        quantity: 1,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt03.jpeg",
      },
      {
        model: "HJ9803",
        brand: "HP",
        ram: "8GB",
        mrp: "70$",
        price: "50$",
        hardDisk: "500GB",
        rating: "4",
        processor: "i3",
        quantity: 14,
        image:
          "https://github.com/edufectcode/resources/raw/main/images/laptops1/lt04.jpeg",
      },
    ],
  };
  module.exports.allLaptops = allLaptops;
  